import {
  type InferGetServerSidePropsType,
  type GetServerSidePropsContext,
} from "next";
import { createServerSideHelpers } from "@trpc/react-query/server";
import SuperJSON from "superjson";
import { appRouter } from "~/server/api/root";
import { db } from "~/server/db";
import { api } from "~/utils/api";
import Layout from "~/components/layout";
import PostView from "~/components/PostView";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import CreateReplyWizard from "~/components/CreateReplyWizard";
import { FaHeart } from "react-icons/fa";
import { useUser } from "@clerk/nextjs";
import ReplyView from "~/components/ReplyView";
import { LoadingPage } from "~/components/loading";

dayjs.extend(relativeTime);

const SinglePostPage = (
  props: InferGetServerSidePropsType<typeof getServerSideProps>,
) => {
  const ctx = api.useUtils();
  const user = useUser();
  const { mutate: likeAReply, isLoading: isLikingAReply } =
    api.like.like.useMutation({
      onSuccess: () => {
        void ctx.invalidate();
      },
    });
  const { data: replies, isLoading: areRepliesLoading } =
    api.reply.getRepliesByPostId.useQuery({ postId: props.postId });

  const { data, isLoading } = api.post.getPostById.useQuery({
    postId: props.postId,
  });
  if (!data)
    return (
      <Layout>
        <h1>Something went wrong</h1>
      </Layout>
    );
  if (isLoading)
    return (
      <Layout>
        <h1>Loading...</h1>
      </Layout>
    );
  return (
    <>
      <Head>
        <title>{`${data.post.content}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PostView post={data} postPage />
        <CreateReplyWizard postId={props.postId} />
        <p className="border-b border-slate-600 py-2 pl-8 text-xl">Replies</p>
        {areRepliesLoading ? (
          <LoadingPage />
        ) : (
          replies?.map((reply) => (
            <ReplyView key={reply.reply.id} reply={reply} />
          ))
        )}
      </Layout>
    </>
  );
};

export default SinglePostPage;

export const getServerSideProps = async (
  context: GetServerSidePropsContext<{ id: string }>,
) => {
  const id = context.params?.id;

  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: {
      db,
      userId: null,
    },
    transformer: SuperJSON,
  });

  if (typeof id !== "string") {
    throw new Error("no id");
  }

  await helpers.post.getPostById.prefetch({ postId: id });

  return {
    props: {
      trpcState: helpers.dehydrate(),
      postId: id,
    },
  };
};
