import Head from "next/head";
import { api } from "~/utils/api";
import Layout from "~/components/layout";
import CreatePostWizard from "~/components/CreatePostWizard";
import Feed from "~/components/Feed";

export default function Home() {
  api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Chirp 🐤</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CreatePostWizard />
        <Feed />
      </Layout>
    </>
  );
}
